[package]
name = "regex-speed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.13", features = ["derive"] }
open = "5.0.1"
plotters = "0.3.5"
rand = "0.8.5"
regex = "1.10.2"
